/*Gênero da categoria Ficção*/
INSERT INTO genero (genero_nome, categoria_cod) VALUES
('Ficção', 1), 
('Romance', 1), 
('Aventura', 1), 
('Mistério', 1), 
('Filosófico', 1); 

/*Gênero da categoria Não ficção*/
INSERT INTO Genero (genero_nome, categoria_cod) VALUES 
('Filosofia e Ciências Sociais ', 2), 
('Economia e Finanças', 2), 
('Desenvolvimento Pessoal' , 2), 
('Saúde', 2), 
('Arte e Design', 2), 
('Tecnologia e Computação' , 2), 
('Estatística e Matemática Aplicada' , 2), 
('Biografia' , 2); ,,,,,,,

/*Gênero da categoria Poesia*/
INSERT INTO Genero (genero_nome, categoria_cod) VALUES 
('Poesia Lírica', 3), 
('Poesia Social', 3), 
('Poesia Modernista', 3), 
('Poesia Filosófica/Existencial ', 3), 
('Poesia Mística/Espiritual', 3), 
('Poesia Simbolista', 3), 
('Antologia Poética', 3), 
('Poesia Visual/Construtiva', 3), 
('Poesia Identitária', 3), 
('Poesia ', 3); 

/*Gênero da categoria Infantis*/
INSERT INTO Genero (genero_nome, categoria_cod) VALUES
('Infantil', 4), 
('Juvenil', 4),  
('Lenda Indígena', 4); 
